<div class="page-header container-fluid">    
    <?php if(!empty($titulo)) { ?>
    <script type="text/javascript">        
        changeTitle('<?php echo $proceso; ?>');
        <?php 
        
        if(Session::get('change_url') === TRUE) {             
            Session::set('change_url', FALSE);
            extract(Router::get());
            $url = "$controller/$action";
            if($module) {
                $url = "$module/$url";
            }
            if($parameters) {
                $params = join('/', $parameters);
                $params = explode('page.', $params);
                if($params[0]) {
                    $url = "$url/".trim($params[0], '/');
                }
            }
            $url = rtrim($url, '/').'/';
            ?>            
            try {
                updateUrl('<?php echo $url; ?>');
            } catch(e) {

            }
            <?php
        }
        ?>
       
    </script>
    <?php } ?>
    <div class="row">
        <div class="col-md-8">
            <h4>
                <?php echo ucfirst($modulo); ?>
                <?php if(isset($proceso) && $proceso!=null) { $proceso = explode(' |', $proceso); echo " | <small>",ucfirst(trim($proceso[0])),"</small>"; } ?>
            </h4>
        </div>
        <div class="col-md-4" id="opt-process"></div>
    </div>       
</div>