<?php View::flash(); ?>

<script type="text/javascript">
    $(function() { $('table').kgrid();});
</script>

<div class="container shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">
                <?php echo DwHtml::button("sistema/sucesos/", 'listar', NULL, 'fa-check', APP_AJAX); ?>
            </div>            
        </div>
    </div>
    
    <div class="container-overflow">
    
        <table class="table table-bordered table-hover table-striped table-condensed">
            <thead>
                <tr>
                    <th style="width: 15px;">NUM</th>
                    <th>FECHA</th>
                    <th>TIPO</th>                    
                    <th>DESCRIPCION</th>                    
                </tr>
            </thead>
            <tbody>
                <?php if($loggers->items) { ?>                                
                    <?php foreach($loggers->items as $log): ?>
                    <tr>
                        <td><?php echo $loggers->counter; ?></td>
                        <td><?php echo $log['fecha']; ?></td>
                        <td>
                            <?php if($log['tipo'] == 'ERROR' OR $log['tipo'] == 'ALERT') { ?>
                                <span class="label label-danger"><?php echo $log['tipo']; ?></span>
                            <?php } else if($log['tipo'] == 'WARNING' OR $log['tipo'] == 'CRITICAL' OR $log['tipo'] == 'EMERGENCE') { ?>
                                <span class="label label-warning"><?php echo $log['tipo']; ?></span>
                            <?php } else if($log['tipo'] == 'NOTICE' OR $log['tipo'] == 'INFO') { ?>
                                <span class="label label-info"><?php echo $log['tipo']; ?></span>
                            <?php } else { ?>
                                <span class="label label-default"><?php echo $log['tipo']; ?></span>
                            <?php } ?>
                        </td>
                        <td><?php echo $log['descripcion']; ?></td>
                    </tr>
                    <?php $loggers->counter++; ?>
                    <?php endforeach; ?>
                <?php } ?>
            </tbody>
        </table>
        
    </div>
    
    <?php View::partial('paginators/default', false, array('page'=>$loggers, 'url'=>"sistema/sucesos/listar/$fecha/")); ?>

    
</div>