<!DOCTYPE html>
<html lang="es">
    <head>
        <title><?php echo $page_title; ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?php echo APP_CHARSET; ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="robots" content="noindex,nofollow" /> 
        <link rel="shortcut icon" href="<?php echo PUBLIC_PATH; ?>img/favicon.ico" type="image/x-icon" />
        <?php Tag::css('bootstrap/bootstrap.min'); ?>
        <?php Tag::css('bootstrap/bootstrap-theme.min'); ?>        
        <?php Tag::css('bootstrap/bootstrap-datetimepicker.min'); ?>
        <?php Tag::css('bootstrap/typehead'); ?>
        <?php Tag::css('file-upload/jquery.fileupload'); ?>
        <?php Tag::css('file-upload/jquery.fileupload-ui'); ?>
        <?php Tag::css('font-awesome.min'); ?>        
        <?php Tag::css('backend/base'); ?>
        <?php Tag::css('backend/style'); ?>
        <?php Tag::css('backend/themes/default/default'); ?>
        <?php echo Html::includeCss(); ?>
        <?php if(!APP_LOCAL) { ?>
            <link href="http://fonts.googleapis.com/css?family=Play:400,700" rel="stylesheet" type="text/css">
        <?php } ?>        
        <?php echo Tag::js('jquery/jquery.min').PHP_EOL; ?>
        <script type="text/javascript">
            function closePopup() { window.close() }
        </script>
    </head>
    <body style="min-width: 800px;">

        <?php View::partial('backend/header_error'); ?>

        <div id="shell-load" style="min-height: 350px">
            <div id="shell-content" class="container">
                <?php View::content(); ?>
            </div>
        </div>

        <?php View::partial('backend/footer'); ?>

    </body>
</html>
