<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

        <div class="row">
            <div class="col-md-4">
                <?php echo DwForm::text('recurso.modulo', array('class'=>'input-lower'), NULL, 'Módulo'); ?>
            </div>
            <div class="col-md-4">
                <?php echo DwForm::text('recurso.controlador', array('class'=>'input-lower input-required'), NULL, 'Controlador'); ?>
            </div>
            <div class="col-md-4">
                <?php echo DwForm::text('recurso.accion', array('class'=>'input-lower'), NULL, 'Acción'); ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8">
                <?php echo DwForm::textarea('recurso.descripcion', array('class'=>'input-lower input-required'), NULL, 'Descripción'); ?>
            </div>
        </div>

        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar recurso'); ?>
                <?php echo DwForm::cancel(); ?>
                <?php echo DwForm::focus('recurso.modulo'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
