<?php View::flash(); ?>

<div class="container shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
            
    <?php echo DwForm::open(); ?>
    
    <div class="row">
        <div class="col-md-3">
            <?php echo DwForm::date('corte', array('class'=>'input-required'), date("Y-m-d"), 'Día'); ?>
        </div>
    </div>
    
    <div class="row">
        <div class="form-actions">
            <?php echo DwForm::send('Listar auditorías', 'fa-check-square-o', NULL, 'mostrar'); ?>            
            <?php echo DwForm::cancel(); ?>
            <?php echo DwForm::focus('corte'); ?>
        </div>
    </div>
    
    <?php echo DwForm::close(); ?>
</div>