<?php View::flash(); ?>

<script type="text/javascript">
    $(function() {
        $('table').kgrid({            
            form_to         : $.KumbiaPHP.publicPath+'sistema/accesos/buscar/',            
            order_attr      : '<?php echo (APP_AJAX) ? 'class="js-link js-spinner"' : ''; ?>',
            order_to        : $.KumbiaPHP.publicPath+'sistema/accesos/listar/'            
        });
    });
</script>

<div class="container shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <div class="container-overflow">
    
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-hidden" data-search="fecha" data-order="fecha">FECHA</th>
                    <th class="col-hidden">HORA</th>
                    <th data-search="nombre" data-order="nombre">NOMBRE</th>
                    <th data-search="apellido" data-order="apellido">APELLIDO</th>
                    <th data-search="ip" data-order="ip">IP</th>
                    <th data-search="tipo_acceso" data-order="tipo_acceso">TIPO ACCESO</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($accesos->items as $acceso): ?>
                    <tr>
                        <td><?php echo $accesos->counter; ?></td>
                        <td><?php echo date("Y-m-d", strtotime($acceso->acceso_at)); ?></td>
                        <td><?php echo date("H:i:s", strtotime($acceso->acceso_at)); ?></td>
                        <td><?php echo $acceso->nombre; ?></td>
                        <td><?php echo $acceso->apellido; ?></td>
                        <td><?php echo $acceso->ip; ?></td>
                        <td><?php echo ($acceso->tipo_acceso == Acceso::ENTRADA) ? '<span class="label label-success">Entrada</span>' : '<span class="label label-danger">Salida</span>'; ; ?></td>
                    </tr>
                    <?php $accesos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
        
    </div>
    
    <?php View::partial('paginators/default', false, array('page'=>$accesos, 'url'=>"sistema/accesos/listar/$order/")); ?>

    
</div>