<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

        <div class="row">
            <div class="col-md-6">
                <?php echo DwForm::text('backup.denominacion', array('class'=>'input-required'), NULL, 'Denominación'); ?>
            </div>
        </div>

        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Crear copia de seguridad'); ?>                
                <?php echo DwForm::cancel(); ?>
                <?php echo DwForm::focus('backup.denominacion'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>