<header class="navbar navbar-inverse navbar-fixed-top user-nav" role="banner">
    
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Menú principal</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <?php echo DwHtml::link('dashboard', DwHtml::img("kumbiaphp.png", APP_NAME, array('style'=>'height: 30px; margin-top: 2.5%')), '' , FALSE); ?>                
        </div>
        
        <div class="pull-right">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><i class="icon-user"></i> <?php echo Session::get('login'); ?> <b class="caret"></b></a>
                    <ul class="dropdown-menu" role="menu" style="left: auto; right: 0 !important">                                
                        <li><?php echo DwHtml::link('sistema/mi_cuenta/', 'Perfil'); ?></li>
                        <li class="divider"></li>
                        <li><?php echo DwHtml::link('sistema/login/salir', 'Salir', array('class'=>'no-load'), 'icon-off', FALSE); ?></li>                
                    </ul>
                </li>
            </ul>
        </div>       
        
    </div>    
    
    <div class="visible-xs">            
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <?php echo DwMenu::phone(); ?>                
        </nav>        
    </div>
    
</header>