<header class="navbar navbar-inverse navbar-fixed-top user-nav" role="banner">
    
    <div class="container">
        
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Menú principal</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <?php echo DwHtml::img("kumbiaphp.png", APP_NAME, array('style'=>'height: 30px; margin-top: 2.5%')); ?>                
        </div>
                
    </div>    
        
</header>