<?php View::flash(); ?>

<div class="container shell-view">
    
    <div class="jumbotron">
        <h1><small>Daily Backend Manager - DBKM</small></h1>
        <p class="">El DBKM es un módulo de administración y configuración del sistema.</p>
        <p class="">Por medio del DBKM podrás gestionar de manera 
            rápida y segura los usuarios, perfiles, recursos, menús, y mucho más!.</p>
        <p class="text-right">
            <a class="btn btn-primary btn-large" href="http://github.com/argordmel/dbkm/" target="_blank"><i class="fa fa-expand fa fa-github fa fa-2x"></i> Ver proyecto en GitHub</a>
        </p>
    </div>
        
    <div class="row">
        <div class="col-md-4">
            <h4><i class="fa fa-expand fa fa-fullscreen fa fa-2x"></i> 100% Responsivo</h4>
            Basado en Bootstrap de Twitter, provee un diseño adaptado a todo tipo de pantalla.
        </div>
        <div class="col-md-4">
            <h4><i class="fa fa-expand fa fa-ok fa fa-2x"></i> 100% Cuztomizable</h4>
            Puedes personalizar el backend con temas, apariencias y variables de configuración
        </div>
        <div class="col-md-4">
            <h4><i class="fa fa-expand fa fa-group fa fa-2x"></i> 100% OpenSource</h4>
            El DBKM está licenciado bajo la New BSD, lo cual te provee de toda una libertad a nivel de programación
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-4">
            <h4><i class="fa fa-expand fa fa-cogs fa fa-2x"></i> Arquitectura MVC</h4>
            Realizado bajo el patrón de diseño MVC y construido con la solidez de KumbiaPHP
        </div>
        <div class="col-md-4">
            <h4><i class="fa fa-expand fa fa-magic fa fa-2x"></i> RICH App </h4>
            El DBKM está construido para ser utilizado en su totalidad con AJAX, aunque si lo prefieres, también responde a peticiones normales
        </div>
        <div class="col-md-4">
            <h4><i class="fa fa-expand fa fa-asterisk fa fa-2x"></i> Características</h4>
            <ul>
                <li>Rápido escalado</li>
                <li>Diseño orientado al usuario final</li>
                <li>Rápido, sencillo y estable gracias al poder de KumbiaPHP</li>
                <li>Control de autidorías y sucesos del sistema</li>
            </ul>
        </div>
    </div>              
    
</div>