<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>


    <?php echo DwForm::open(); ?>

    <div class="row">
        <div class="col-md-12">
            <?php echo DwForm::textarea('estado_usuario.descripcion', array('class'=>'input-required mask-text'), NULL, 'Motivo del cambio de estado'); ?>
        </div>
    </div>

    <div class="row">
        <div class="form-actions">
            <?php echo DwForm::send('Actualizar estado'); ?>
            <?php echo DwForm::cancel(); ?>            
        </div>
    </div>

    <?php echo DwForm::focus('estado_usuario.descripcion'); ?>
    
    <?php echo DwForm::close(); ?>

</div>
