<?php View::flash(); ?>

<script type="text/javascript">
    function onSend() {          
        var bValid = true;                
        var login = $("#login");
        var pass = $("#password");                
        bValid = bValid && checkLength(login, 4, 0, "El usuario");
        if (bValid) { removeError(login); }
        bValid = bValid && checkLength(pass, 4, 0, "La contraseña");
        if (bValid) { removeError(login); }
        bValid = bValid && checkRegexp(login, /^([A-ZÑ0-9])+$/i, "El usuario debe tener caracteres alfanuméricos.");
        if (bValid) { removeError(login); }
        bValid = bValid && checkRegexp(pass, /^([A-ZÑ0-9\.\-\#\?\_])+$/i, "La contraseña debe tener caracteres [A-Z]-[0-9]-[#?.-]");
        if (bValid) { removeError(pass); }
        return bValid;
    }
</script>

<div class="account-container">

    <div class="content clearfix">

        <?php echo DwForm::open('sistema/login/entrar/', '', array('class'=>'no-ajax form-validate', 'id'=>'formulario', 'before-send'=>'onSend();')); ?>

            <?php echo DwForm::focus('login'); ?>

            <noscript><h5 style="text-align: center;">¡Tu navegador no soporta Javascript!.. Activa el uso de Javascript en tu navegador.</h5></noscript>

            <div class="text-center" style="width: 100%; margin: 0 auto;">
                <?php echo DwHtml::img('kumbiaphp.png', '',  array('style'=>'margin-top: 18px; height: 40px;'));?>
            </div>

            <div class="container login-fields">
                
                <h5>Iniciar Sesión:</h5>  
                                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="field form-group">
                            <label for="login">Usuario:</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                <input type="text" id="login" name="login" value="" placeholder="Usuario" class="form-control login username-field" />
                            </div>
                        </div>                        
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="field form-group">
                            <label for="password">Contraseña:</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-key"></i></span>
                                <input type="password" id="password" name="password" value="" placeholder="Contraseña" class="form-control login password-field span10"/>
                            </div>
                        </div>
                    </div>                    
                </div>
                

                <div>
                    <?php echo DwForm::hidden('mode', null, 'auth'); ?>
                </div>

                <div>
                    <?php echo DwForm::token(); ?>
                </div>

            </div>

            <div class="row">
                <div class="login-actions">
                    <div class="pull-right" style="padding-right: 20px;">
                        <?php echo DwForm::btnSubmit('Entrar', array('class'=>'btn btn-warning btn-large'), 'fa-sign-in'); ?>
                    </div>
                </div>
            </div>

        <?php echo DwForm::close(); ?>

    </div>

</div>

<div class="login-extra">
    Recuperar <?php echo DwHtml::link('#', 'contraseña', array('data-target'=>'#resetPassword', 'data-toggle'=>'modal')); ?>
</div>

<?php echo DwJs::alert('Para recuperar tu contraseña puedes contactar al administrador del sistema o contactarnos a través de los siguientes medios: ', 'subtext: E-mail: email@example.com <br /> Teléfono: 123 456 78 90', 'title: Recuperación de contraseña', 'name: resetPassword', 'icon: fa-question-sign'); ?>
