<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">

                <?php echo DwHtml::button("sistema/configuracion/", 'basic', NULL, 'fa-asterisk', APP_AJAX); ?>
                <?php echo DwHtml::button("sistema/configuracion/config/", 'config all', array('class'=>'btn-success active'), 'fa-asterisk', APP_AJAX); ?>
                <?php echo DwHtml::button("sistema/configuracion/routes/", 'routes', NULL, 'fa-random', APP_AJAX); ?>
                <?php echo DwHtml::button("sistema/configuracion/databases/", 'databases', NULL, 'fa-hdd-o', APP_AJAX); ?>

                <div class="pull-right">
                    <?php echo DwHtml::button("sistema/configuracion/reset/", 'reset', array('class'=>'btn-danger js-confirm', 'msg-title'=>'Restarurar archivos de configuración', 'msg'=>'Está seguro de querer restastaurar los archivos de configuración? <br />Recuerda que esta operación no se puede reversar.'), 'fa-warning', APP_AJAX); ?>
                </div>

            </div>
        </div>
    </div>

    <?php echo DwForm::open(); ?>

        <div class="row">
            <div class="col-md-1">&nbsp;</div>

            <div class="col-md-5">

                <?php echo DwForm::fieldset("Configuración de la aplicación"); ?>

                    <?php echo DwForm::text('application.name', array('class'=>'input-required'), $config['application']['name'], 'Nombre del proyecto:'); ?>

                    <?php echo DwForm::text('application.timezone', array('class'=>'input-required'), $config['application']['timezone'], 'Timezone:'); ?>

                    <?php echo DwForm::select('application.production', array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required'), $config['application']['production'], 'Proyecto en producción:'); ?>

                    <?php echo DwForm::select('application.database', array('development'=>'Development', 'production'=>'Production'), array('class'=>'input-required'), $config['application']['database'], 'Entorno de conexión:'); ?>

                    <?php echo DwForm::text('application.dbdate', array('class'=>'input-required'), $config['application']['dbdate'], 'Formato de fechas:'); ?>

                    <?php echo DwForm::select('application.debug', array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required'), $config['application']['debug'], 'Debug:'); ?>

                    <?php echo DwForm::select('application.log_exceptions', array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required'), $config['application']['log_exceptions'], 'Mostrar excepciones:'); ?>

                    <?php echo DwForm::text('application.charset', array('class'=>'input-required'), $config['application']['charset'], 'Juego de caracteres:'); ?>

                    <?php echo DwForm::text('application.cache_driver', array('class'=>'input-required'), $config['application']['cache_driver'], 'Driver de caché:'); ?>

                    <?php echo DwForm::hidden('application.metadata_lifetime', null, $config['application']['metadata_lifetime']); ?>

                    <?php echo DwForm::hidden('application.namespace_auth', null, $config['application']['namespace_auth']); ?>

                    <?php echo DwForm::select('application.routes', array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required'), $config['application']['routes'], 'Habilitar el routes:'); ?>

                <?php echo DwForm::fieldset(); ?>

            </div>

            <div class="col-md-1">&nbsp;</div>

            <div class="col-md-5">
                <?php echo DwForm::fieldset("<a id='add-config' href='#form-add-config' class='btn btn-default' data-toggle='modal'><i class='fa fa-check fa-pd-expand'></i>Agregar parámetro</a>"); ?>
                <?php if(isset($config['custom'])) { ?>
                    <?php foreach($config['custom'] as $campo => $valor): ?>
                        <?php
                        switch ($campo) {
                            case 'app_update':      $text = 'Sistema en actualización';
                                                    break;
                            case 'app_update_time': $text = 'Tiempo de la actualización';
                                                    break;
                            case 'app_version':     $text = 'Versión de la aplicación';
                                                    break;
                            case 'app_logger':      $text = 'Generar logs de la base de datos';
                                                    break;
                            case 'app_office':      $text = 'Manejo de sucursales de la empresa';
                                                    break;
                            case 'app_ajax':        $text = 'Cargar con AJAX';
                                                    break;
                            case 'app_local':       $text = 'La aplicación se encuentra en el localhost';
                                                    break;
                            case 'login_exclusion': $text = 'Nombre de usuarios excluidos';
                                                    break;
                            case 'datagrid':        $text = 'Cantidad de datos por página en los reportes';
                                                    break;
                            default:                $text = $campo;
                                                    break;
                        }
                        ?>
                        <?php if ( in_array($valor , array('On', 'Off')) ) {  ?>
                            <?php echo DwForm::select("custom.$campo", array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required'), $valor, ucfirst($text)); ?>
                        <?php } else { ?>
                            <?php echo DwForm::text("custom.$campo", array('class'=>'input-lower input-required'), $valor, ucfirst($text)); ?>
                        <?php } ?>
                    <?php endforeach; ?>
                <?php } ?>

                <div id="append-config"></div>
                <p>Los campos creados se definirán automáticamente al cargar el aplicativo y se almacenarán en el config.ini</p>
                <p>Para eliminar una variable puede colocar el valor "delete-var" en el input.</p>

                <?php echo DwForm::fieldset(); ?>

            </div>
        </div>

        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar configuración'); ?>
                <?php echo DwForm::cancel(); ?>
            </div>
        </div>


    <?php echo DwForm::close(); ?>


</div>

<div class="modal fade" tabindex="-1" id="form-add-config" role="dialog" aria-labelledby="form-add-config" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php echo DwForm::open('', '', array('id'=>'form-modal', 'class'=>'')); ?>    
            <div class="modal-header">                
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3>Agregar variable de configuración</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-5">
                        <?php echo DwForm::text('variable', array('class'=>'input-lower input-required'), null, 'Nombre de la variable'); ?>
                    </div>
                    <div class="col-md-5">
                        <?php echo DwForm::text('valor', array('class'=>'input-lower input-required'), null, 'Valor'); ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <?php echo DwForm::submit("Crear", array('class'=>'btn btn-primary')); ?>
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancelar</button>
            </div>
            <?php echo DwForm::close(); ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        $("#form-modal").submit(function(){            
            variable = $('#variable');
            valor = $("#valor");
            $('<div class="form-group">'+
            '<label for="custom_'+variable.val()+'" class="control-label">'+variable.val()+':<span class="req">*</span></label>'+                
            '<input id="custom_'+variable.val()+'" name="custom['+variable.val()+']" type="text" value="'+valor.val()+'" class="form-control input-lower input-required" required="required">'+
            '<p class="help-block"> <span class="help-error" id="err_custom_'+variable.val()+'">&nbsp; </span></p>'+
            '</div>').appendTo('#append-config');
            variable.attr('value', '');
            valor.attr('value', '');
            jsSpinner('hide');
            $("#form-add-config").modal('hide');            
            return false;
        });
    });
</script>