<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">            
            <div class="btn-actions">
                <?php echo DwHtml::button("sistema/configuracion/", 'basic', array('class'=>'btn-success active'), 'fa-asterisk', APP_AJAX); ?>
                <?php echo DwHtml::button("sistema/configuracion/config/", 'config all', array('class'=>'btn-info'), 'fa-asterisk', APP_AJAX); ?>
                <?php echo DwHtml::button("sistema/configuracion/routes/", 'routes', array('class'=>'btn-info'), 'fa-random', APP_AJAX); ?>
                <?php echo DwHtml::button("sistema/configuracion/databases/", 'databases', array('class'=>'btn-info'), 'fa-hdd-o', APP_AJAX); ?>
                <div class="pull-right">
                    <?php echo DwHtml::button("sistema/configuracion/reset/", 'reset', array('class'=>'btn-danger js-confirm', 'msg-title'=>'Restarurar archivos de configuración', 'msg'=>'Está seguro de querer restastaurar los archivos de configuración? <br />Recuerda que esta operación no se puede reversar.'), 'fa-warning', APP_AJAX); ?>
                </div>
            </div>
        </div>
    </div>

    <?php echo DwForm::open(); ?>

        <div class="row">
            <div class="col-md-1">&nbsp;</div>

            <div class="col-md-4">

                <?php echo DwForm::fieldset("Configuración básica"); ?>

                    <?php echo DwForm::text('application.name', array('class'=>'input-lower input-required'), $config['application']['name'], 'Nombre del proyecto:'); ?>

                    <?php echo DwForm::text('application.timezone', array('class'=>'input-lower input-required'), $config['application']['timezone'], 'Timezone:'); ?>

                    <?php echo DwForm::select('application.production', array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required'), $config['application']['production'], 'Proyecto en producción:'); ?>

                    <?php echo DwForm::select('application.database', array('development'=>'Development', 'production'=>'Production'), array('class'=>'input-required'), $config['application']['database'], 'Entorno de conexión:'); ?>

                <?php echo DwForm::fieldset(); ?>

            </div>

            <div class="col-md-1">&nbsp;</div>

            <div class="col-md-4">                
                <?php echo DwForm::fieldset("Configuración personalizada"); ?>
                <?php if(isset($config['custom'])) { ?>
                    <?php foreach($config['custom'] as $campo => $valor): ?>
                        <?php
                        if($campo == 'app_logger' OR $campo=='app_office' OR $campo=='pag_min' OR $campo=='pag_med' OR $campo=='pag_max' OR $campo=='pag_ext') {
                            continue;
                        }
                        ?>
                        <?php
                        switch ($campo) {
                            case 'app_update':      $text = 'Sistema en mantenimiento';
                                                    break;
                            case 'app_update_time': $text = 'Tiempo de la mantenimiento';
                                                    break;
                            case 'app_version':     $text = 'Versión de la aplicación';
                                                    break;
                            case 'app_logger':      $text = 'Generar logs de la base de datos';
                                                    break;
                            case 'app_office':      $text = 'Manejo de sucursales de la empresa';
                                                    break;
                            case 'app_ajax':        $text = 'Cargar con AJAX';
                                                    break;
                            case 'app_local':       $text = 'La aplicación se encuentra en el localhost';
                                                    break;
                            case 'login_exclusion': $text = 'Nombre de usuarios excluidos';
                                                    break;
                            case 'datagrid':        $text = 'Cantidad de datos por página en los reportes';
                                                    break;
                            default:                $text = $campo;
                                                    break;
                        }
                        ?>
                        <?php if ( in_array($valor , array('On', 'Off')) ) {  ?>
                            <?php echo DwForm::select("custom.$campo", array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required'), $valor, ucfirst($text)); ?>
                        <?php } else { ?>
                            <?php echo DwForm::text("custom.$campo", array('class'=>'input-lower input-required'), $valor, ucfirst($text)); ?>
                        <?php } ?>
                    <?php endforeach; ?>
                <?php } ?>

                <div id="append-config"></div>
                <p>Los campos creados se definirán automáticamente al cargar el aplicativo y se almacenarán en el config.ini</p>
                <p>Para eliminar una variable puede colocar el valor "delete-var" en el input.</p>

                <?php echo DwForm::fieldset(); ?>

            </div>
        </div>

        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar configuración'); ?>
                <?php echo DwForm::cancel(); ?>
            </div>
        </div>


    <?php echo DwForm::close(); ?>


</div>