<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">
                <?php echo DwHtml::button("sistema/configuracion/", 'basic', NULL, 'fa-asterisk', APP_AJAX); ?>
                <?php echo DwHtml::button("sistema/configuracion/config/", 'config all', NULL, 'fa-asterisk', APP_AJAX); ?>
                <?php echo DwHtml::button("sistema/configuracion/routes/", 'routes', array('class'=>'btn-success active'), 'fa-random', APP_AJAX); ?>
                <?php echo DwHtml::button("sistema/configuracion/databases/", 'databases', NULL, 'fa-hdd-o', APP_AJAX); ?>

                <div class="pull-right">
                    <?php echo DwHtml::button("sistema/configuracion/reset/", 'reset', array('class'=>'btn-danger js-confirm', 'confirm-title'=>'Restarurar archivos de configuración', 'confirm-body'=>'Está seguro de querer restastaurar los archivos de configuración? <br />Recuerda que esta operación no se puede reversar.'), 'fa-warning', APP_AJAX); ?>
                </div>
            </div>
        </div>
    </div>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'no-validate')); ?>    

        <div class="row">
            <div class="col-md-1">&nbsp;</div>

            <div class="col-md-4">
                <?php echo DwForm::fieldset("<a id='add-config' href='#form-add-config' class='btn btn-default' data-toggle='modal'><i class='fa fa-check fa-pd-expand'></i>Agregar enrutamiento</a>"); ?>

                <?php if(isset($routes['routes'])) { ?>
                    <?php foreach($routes['routes'] as $campo => $valor): ?>
                        <?php if($campo=='/') { ?>
                            <?php echo DwForm::text("routes.$campo", array('class'=>'input-lower input-required'), 'principal', $campo, 'Controlador principal'); ?>
                        <?php } else if($campo=='/status/') { ?>
                            <?php echo DwForm::hidden("routes.$campo", null, $valor); ?>
                        <?php } else if($campo=='/sistema/instalacion/*' or $campo=='/*') { ?>
                            <?php echo DwForm::hidden("routes.$campo", null, 'delete-var'); ?>
                        <?php } else { ?>
                            <?php echo DwForm::text("routes.$campo", array('class'=>'input-lower input-required'), $valor, $campo); ?>
                        <?php } ?>
                    <?php endforeach; ?>
                <?php } ?>

                <div id="append-config"></div>
                <p>Para anular una regla puede colocar el valor "delete-var" en el input.</p>
                <?php echo DwForm::fieldset(); ?>

            </div>
        </div>

        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar enrutamiento'); ?>
                <?php echo DwForm::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>


<div class="modal fade" tabindex="-1" id="form-add-config" role="dialog" aria-labelledby="form-add-config" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php echo DwForm::open('', '', array('id'=>'form-modal', 'class'=>'')); ?>    
            <div class="modal-header">                
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3>Sistema de enrutamiento</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-5">
                        <?php echo DwForm::text('variable', array('class'=>'input-lower input-required'), null, 'Ruta'); ?>
                    </div>
                    <div class="col-md-5">
                        <?php echo DwForm::text('valor', array('class'=>'input-lower input-required'), null, 'Redirección'); ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <?php echo DwForm::submit("Crear", array('class'=>'btn btn-primary')); ?>
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancelar</button>
            </div>
            <?php echo DwForm::close(); ?>
        </div>
    </div>
</div>
       
<script type="text/javascript">
    $(function(){
        $("#form-modal").submit(function(){            
                variable = $('#variable');
                valor = $("#valor");
                $('<div class="form-group">'+
                '<label for="routes_'+variable.val()+'" class="control-label">'+variable.val()+'<span class="req">*</span></label>'+                
                '<input id="routes_'+variable.val()+'" name="routes['+variable.val()+']" type="text" value="'+valor.val()+'" class="form-control input-lower input-required" required="required">'+
                '<p class="help-block"> <span class="help-error" id="err_routes_'+variable.val()+'">&nbsp; </span></p>'+
                '</div>').appendTo('#append-config');
                variable.attr('value', '');
                valor.attr('value', '');
                jsSpinner('hide');
                $("#form-add-config").modal('hide');
            return false;
        });
        $("#form").submit(function(){
            var req = $(this).find('.input-required');
            var err = 0;
            req.each(function(){
                if($(this).val() == '' || $(this).val().length == 0) {
                    err++;
                }
            });
            if(err > 0) {
                try {
                    errorForm();
                } catch(e) { alert('Los campos marcados con (*) son requeridos.')}
                return false;
            }
            return true;
        });
    });
</script>
