<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

        <div class="row">
            <div class="col-md-4">
                <?php echo DwForm::text('menu.menu', array('class'=>'input-lower input-required'), NULL, 'Título'); ?>
            </div>
            <div class="col-md-4">
                <?php echo DwForm::dbSelect('menu.menu_id', 'menu', array('sistema/menu', 'getListadoMenu', Menu::ACTIVO), 'Ninguno', array('class'=>'input-lower'), NULL, 'Menú padre'); ?>

            </div>
            <div class="col-md-4">
                <?php echo DwForm::dbSelect('menu.recurso_id', 'recurso', array('sistema/recurso', 'getListadoRecurso', Recurso::ACTIVO), 'Ninguno', array('class'=>'input-lower'), NULL, 'Recurso'); ?>
            </div>
        </div>
    
        <div class="row">
            <div class="col-md-4">
                <?php echo DwForm::text('menu.posicion', array('class'=>'input-integer mask-pint'), NULL, 'Posición'); ?>
            </div>
            <div class="col-md-4">
                <?php echo DwForm::text('menu.icono', array('class'=>'input-lower'), NULL, 'Icono a mostrar'); ?>
            </div>
            <div class="col-md-4">
                <?php echo DwForm::text('menu.url', array('class'=>'input-required input-lower'), NULL, 'URL'); ?>
            </div>
        </div>
    
        <div class="row">
            <div class="col-md-4">
                <?php echo DwForm::select('menu.visibilidad', array(Menu::BACKEND=>'Backend', Menu::FRONTEND=>'Frontend'), array('class'=>'input-lower input-required'), Menu::BACKEND, 'Visibilidad'); ?>
            </div>
        </div>
    
        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar menú'); ?>
                <?php echo DwForm::cancel(); ?>
                <?php echo DwForm::focus('menu.menu'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>

<script type="text/javascript" >
    $(function(){
        $("#menu_recurso_id").on('change',function(){
            var recurso = $('option:selected',this).text();
            $("#menu_url").val(recurso.replace('/*','/'));
        });
    });
</script>