<?php View::flash(); ?>

<script type="text/javascript">
    $(function() {
        $('table').kgrid({
            order_to:   $.KumbiaPHP.publicPath+"sistema/menus/listar/",
            order_attr: '<?php echo (APP_AJAX) ? 'class="js-link js-spinner"' : ''; ?>'
        });
    });
</script>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">            
            <div class="btn-actions">
                <?php echo DwHtml::button("sistema/menus/agregar/", 'agregar', NULL, 'fa-check-square-o', APP_AJAX); ?>
            </div>
        </div>
    </div>
         
    <ul class="nav nav-tabs nav-justified">
        <?php $counter = 1; ?>
        <?php if($front) { ?>
            <li class="<?php echo ($counter==1) ? 'active' : '';?>"><a href="<?php echo '#tab'.$counter; ?>" data-toggle="tab">Frontend</a></li>
            <?php $counter++; ?>            
        <?php } ?>
        <?php foreach($menus as $menu): ?>
            <?php if($menu->visibilidad != Menu::BACKEND) { ?>
                <?php continue;?>
            <?php } ?>
            <li class="<?php echo ($counter==1) ? 'active' : '';?>"><a href="<?php echo '#tab'.$counter; ?>" data-toggle="tab"><?php echo Filter::get($menu->menu, 'ucfirst'); ?></a></li>
            <?php $counter++; ?>
        <?php endforeach; ?>                
    </ul>
   
    <div class="tab-content">
        <?php $counter = 1; ?>
        
        <?php if($front) { ?>
        <div class="tab-pane <?php echo ($counter==1) ? 'active' : '';?>" id="<?php echo 'tab'.$counter; ?>">            
            
            <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                <thead>                    
                    <tr>
                        <th>NUM</th>
                        <th data-order="posicion">POSICION</th>
                        <th data-order="padre">PADRE</th>
                        <th data-order="menu">TITULO</th>
                        <th data-order="recurso">RECURSO</th>
                        <th data-order="url">URL</th>
                        <th class="col-collapse">ICONO</th>
                        <th data-order="visibilidad">VISIBILIDAD</th>
                        <th data-order="activo">ESTADO</th>
                        <th class="btn-actions col-blocked text-center">ACCIONES</th>
                    </tr>                    
                </thead>
                <tbody>
            
                <?php $front = $menu->getListadoMenuPadres(Menu::FRONTEND); ?>
                <?php foreach($front as $menu): ?>
                    <?php if($menu->visibilidad != Menu::FRONTEND) { ?>
                        <?php continue;?>
                    <?php } ?>
                    <?php $key_upd = Security::setKey($menu->id, 'upd_menu'); ?>
                    <?php $key_ina = Security::setKey($menu->id, 'inactivar_menu'); ?>
                    <?php $key_rea = Security::setKey($menu->id, 'reactivar_menu'); ?>
                    <?php $key_del = Security::setKey($menu->id, 'eliminar_menu'); ?>                            
                        <tr>
                            <td></td>                                
                            <td><?php echo $menu->posicion; ?></td>
                            <td></td>
                            <td><?php echo $menu->menu; ?></td>
                            <td><?php echo $menu->recurso; ?></td>
                            <td><?php echo $menu->url; ?></td>
                            <td><?php echo $menu->icono; ?></td>
                            <td><?php echo ($menu->visibilidad == Menu::BACKEND) ? '<span class="label label-success">Backend</span>' : '<span class="label label-warning">Frontend</span>'; ; ?></td>
                            <td><?php echo ($menu->activo == Menu::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-danger">Bloqueado</span>'; ; ?></td>
                            <td>
                                <?php echo DwHtml::buttonTable('Modificar menú', "sistema/menus/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                                <?php if($menu->activo == Menu::ACTIVO) { ?>
                                    <?php echo DwHtml::buttonTable('Bloquear menú', "sistema/menus/estado/inactivar/$key_ina/", null, 'success', 'fa-flag'); ?>
                                <?php } else { ?>
                                    <?php echo DwHtml::buttonTable('Reactivar menú', "sistema/menus/estado/reactivar/$key_rea/", null, 'danger', 'fa-flag'); ?>
                                <?php } ?>
                                <?php echo DwHtml::buttonTable('Eliminar menú', "sistema/menus/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar menú', 'confirm-body'=>'Está seguro de eliminar este menú? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'fa-ban'); ?>
                            </td>
                        </tr>
                        <?php $hijos = $menu->getMenusPorPadre($menu->id, $order); ?>
                        <?php if($hijos) { ?>
                            <?php $counter2 = 1; ?>
                            <?php foreach($hijos as $hijo): ?>
                                <?php $key_upd = Security::setKey($hijo->id, 'upd_menu'); ?>
                                <?php $key_ina = Security::setKey($hijo->id, 'inactivar_menu'); ?>
                                <?php $key_rea = Security::setKey($hijo->id, 'reactivar_menu'); ?>
                                <?php $key_del = Security::setKey($hijo->id, 'eliminar_menu'); ?>
                                <tr>
                                    <td><?php echo $counter.'-'.$counter2; ?></td>                                
                                    <td><?php echo $hijo->posicion; ?></td>
                                    <td><?php echo $hijo->padre; ?></td>
                                    <td><?php echo $hijo->menu; ?></td>
                                    <td><?php echo $hijo->recurso; ?></td>
                                    <td><?php echo $hijo->url; ?></td>
                                    <td><?php echo $hijo->icono; ?></td>
                                    <td><?php echo ($hijo->visibilidad == Menu::BACKEND) ? '<span class="label label-success">Backend</span>' : '<span class="label label-warning">Frontend</span>'; ; ?></td>
                                    <td><?php echo ($hijo->activo == Menu::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-danger">Bloqueado</span>'; ; ?></td>
                                    <td>
                                        <?php echo DwHtml::buttonTable('Modificar menú', "sistema/menus/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                                        <?php if($hijo->activo == Menu::ACTIVO) { ?>
                                            <?php echo DwHtml::buttonTable('Bloquear menú', "sistema/menus/estado/inactivar/$key_ina/", null, 'success', 'fa-flag'); ?>
                                        <?php } else { ?>
                                            <?php echo DwHtml::buttonTable('Reactivar menú', "sistema/menus/estado/reactivar/$key_rea/", null, 'danger', 'fa-flag'); ?>
                                        <?php } ?>
                                        <?php echo DwHtml::buttonTable('Eliminar menú', "sistema/menus/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar menú', 'confirm-body'=>'Está seguro de eliminar este menú? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'fa-ban'); ?>
                                    </td>
                                </tr>     
                                <?php $counter2++; ?>
                            <?php endforeach; ?>
                        <?php } ?>
                    <?php $counter++; ?>
                    <?php endforeach; ?>
                </tbody>                                       
            </table>            
        </div>
        <?php } ?>    
        <?php foreach($menus as $menu): ?>  
            <?php if($menu->visibilidad != Menu::BACKEND) { ?>
                <?php continue;?>
            <?php } ?>
            <?php $key_upd = Security::setKey($menu->id, 'upd_menu'); ?>
            <?php $key_ina = Security::setKey($menu->id, 'inactivar_menu'); ?>
            <?php $key_rea = Security::setKey($menu->id, 'reactivar_menu'); ?>
            <?php $key_del = Security::setKey($menu->id, 'eliminar_menu'); ?>
        
        <div class="tab-pane <?php echo ($counter==1) ? 'active' : '';?>" id="<?php echo 'tab'.$counter; ?>">
            
            <?php $items = $menu->getMenusPorPadre($menu->id, $order); ?>
            
            <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                <thead>                    
                    <tr>
                        <th>NUM</th>
                        <th data-order="posicion">POSICION</th>
                        <th data-order="padre">PADRE</th>
                        <th data-order="menu">TITULO</th>
                        <th data-order="recurso">RECURSO</th>
                        <th data-order="url">URL</th>
                        <th class="col-collapse">ICONO</th>
                        <th data-order="visibilidad">VISIBILIDAD</th>
                        <th data-order="activo">ESTADO</th>
                        <th class="btn-actions col-blocked text-center">ACCIONES</th>
                    </tr>                    
                </thead>
                <tbody>
                    <tr>
                        <td></td>                                
                        <td><?php echo $menu->posicion; ?></td>
                        <td></td>
                        <td><?php echo $menu->menu; ?></td>
                        <td><?php echo $menu->recurso; ?></td>
                        <td><?php echo $menu->url; ?></td>
                        <td><?php echo $menu->icono; ?></td>
                        <td><?php echo ($menu->visibilidad == Menu::BACKEND) ? '<span class="label label-success">Backend</span>' : '<span class="label label-warning">Frontend</span>'; ; ?></td>
                        <td><?php echo ($menu->activo == Menu::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-danger">Bloqueado</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar menú', "sistema/menus/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                            <?php if($menu->activo == Menu::ACTIVO) { ?>
                                <?php echo DwHtml::buttonTable('Bloquear menú', "sistema/menus/estado/inactivar/$key_ina/", null, 'success', 'fa-flag'); ?>
                            <?php } else { ?>
                                <?php echo DwHtml::buttonTable('Reactivar menú', "sistema/menus/estado/reactivar/$key_rea/", null, 'danger', 'fa-flag'); ?>
                            <?php } ?>
                            <?php echo DwHtml::buttonTable('Eliminar menú', "sistema/menus/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar menú', 'confirm-body'=>'Está seguro de eliminar este menú? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'fa-ban'); ?>
                        </td>
                    </tr>
                    <?php if($items) { ?>
                        <?php $counter2 = 1; ?>
                        <?php foreach($items as $row): ?>
                            
                            <?php $key_upd = Security::setKey($row->id, 'upd_menu'); ?>
                            <?php $key_ina = Security::setKey($row->id, 'inactivar_menu'); ?>
                            <?php $key_rea = Security::setKey($row->id, 'reactivar_menu'); ?>
                            <?php $key_del = Security::setKey($row->id, 'eliminar_menu'); ?>

                            <tr>
                                <td><?php echo $counter2; ?></td>                                
                                <td><?php echo $row->posicion; ?></td>
                                <td><?php //echo $row->padre; ?></td>
                                <td><?php echo $row->menu; ?></td>
                                <td><?php echo $row->recurso; ?></td>
                                <td><?php echo $row->url; ?></td>
                                <td><?php echo $row->icono; ?></td>
                                <td><?php echo ($row->visibilidad == Menu::BACKEND) ? '<span class="label label-success">Backend</span>' : '<span class="label label-warning">Frontend</span>'; ; ?></td>
                                <td><?php echo ($row->activo == Menu::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-danger">Bloqueado</span>'; ; ?></td>
                                <td>
                                    <?php echo DwHtml::buttonTable('Modificar menú', "sistema/menus/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                                    <?php if($row->activo == Menu::ACTIVO) { ?>
                                        <?php echo DwHtml::buttonTable('Bloquear menú', "sistema/menus/estado/inactivar/$key_ina/", null, 'success', 'fa-flag'); ?>
                                    <?php } else { ?>
                                        <?php echo DwHtml::buttonTable('Reactivar menú', "sistema/menus/estado/reactivar/$key_rea/", null, 'danger', 'fa-flag'); ?>
                                    <?php } ?>
                                    <?php echo DwHtml::buttonTable('Eliminar menú', "sistema/menus/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar menú', 'confirm-body'=>'Está seguro de eliminar este menú? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'fa-ban'); ?>
                                </td>
                            </tr>
                            
                            <?php $hijos = $row->getMenusPorPadre($row->id, $order); ?>
                            <?php if($hijos) { ?>
                                <?php $counter3 = 1; ?>
                                <?php foreach($hijos as $hijo): ?>
                                    <?php $key_upd = Security::setKey($hijo->id, 'upd_menu'); ?>
                                    <?php $key_ina = Security::setKey($hijo->id, 'inactivar_menu'); ?>
                                    <?php $key_rea = Security::setKey($hijo->id, 'reactivar_menu'); ?>
                                    <?php $key_del = Security::setKey($hijo->id, 'eliminar_menu'); ?>
                                    <tr>
                                        <td><?php echo $counter2.'-'.$counter3; ?></td>                                
                                        <td><?php echo $hijo->posicion; ?></td>
                                        <td><?php echo $hijo->padre; ?></td>
                                        <td><?php echo $hijo->menu; ?></td>
                                        <td><?php echo $hijo->recurso; ?></td>
                                        <td><?php echo $hijo->url; ?></td>
                                        <td><?php echo $hijo->icono; ?></td>
                                        <td><?php echo ($hijo->visibilidad == Menu::BACKEND) ? '<span class="label label-success">Backend</span>' : '<span class="label label-warning">Frontend</span>'; ; ?></td>
                                        <td><?php echo ($hijo->activo == Menu::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-danger">Bloqueado</span>'; ; ?></td>
                                        <td>
                                            <?php echo DwHtml::buttonTable('Modificar menú', "sistema/menus/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                                            <?php if($hijo->activo == Menu::ACTIVO) { ?>
                                                <?php echo DwHtml::buttonTable('Bloquear menú', "sistema/menus/estado/inactivar/$key_ina/", null, 'success', 'fa-flag'); ?>
                                            <?php } else { ?>
                                                <?php echo DwHtml::buttonTable('Reactivar menú', "sistema/menus/estado/reactivar/$key_rea/", null, 'danger', 'fa-flag'); ?>
                                            <?php } ?>
                                            <?php echo DwHtml::buttonTable('Eliminar menú', "sistema/menus/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar menú', 'confirm-body'=>'Está seguro de eliminar este menú? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'fa-ban'); ?>
                                        </td>
                                    </tr>     
                                    <?php $counter3++; ?>
                                <?php endforeach; ?>
                            <?php } ?>                            
                            <?php $counter2++; ?>
                        <?php endforeach; ?>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php $counter++; ?>
        <?php endforeach; ?>
    </div>
  
</div>