<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

        <div class="row">
            <div class="col-md-6">
                <?php echo DwForm::text('perfil.perfil', array('class'=>'input-lower input-required mask-alpha'), NULL, 'Perfil'); ?>
            </div>
            <div class="col-md-6">
                <?php echo DwForm::text('perfil.plantilla', array('class'=>'input-lower mask-alphanum'), NULL, 'Plantilla', 'La plantilla de sebe ubicar dentro la caperta "templates".'); ?>
            </div>
        </div>

        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar perfil'); ?>
                <?php echo DwForm::reset(); ?>
                <?php echo DwForm::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
