<?php View::flash(); ?>

<script type="text/javascript">
    $(function() {
        $('table').kgrid({
            order_to:   $.KumbiaPHP.publicPath+"sistema/perfiles/listar/",
            order_attr: '<?php echo (APP_AJAX) ? 'class="js-link js-spinner"' : ''; ?>'
        });
    });
</script>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">
                <?php echo DwHtml::button("sistema/perfiles/agregar/", 'agregar', NULL, 'fa-check-square-o', APP_AJAX); ?>
            </div>            
        </div>
    </div>

    <div class="container-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th data-order="perfil">PERFIL</th>
                    <th data-order="plantilla">PLANTILLA</th>
                    <th data-order="usuarios">USUARIOS</th>
                    <th data-order="estado">ESTADO</th>
                    <th class="btn-actions col-blocked text-center">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($perfiles->items as $perfil): ?>
                    <?php $key_show = Security::setKey($perfil->id, 'show_perfil'); ?>
                    <?php $key_upd = Security::setKey($perfil->id, 'upd_perfil'); ?>
                    <?php $key_inac = Security::setKey($perfil->id, 'inactivar_perfil'); ?>
                    <?php $key_reac = Security::setKey($perfil->id, 'reactivar_perfil'); ?>
                    <tr>
                        <td><?php echo $perfiles->counter; ?></td>
                        <td><?php echo $perfil->perfil; ?></td>
                        <td><?php echo $perfil->plantilla; ?></td>
                        <td><?php echo $perfil->usuarios; ?></td>
                        <td><?php echo ($perfil->estado == Perfil::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-danger">Bloqueado</span>';?></td>
                        <td class="btn-actions">
                            <?php echo DwHtml::buttonTable('Ver perfil', "sistema/perfiles/ver/$key_show/", null, 'info', 'fa-search'); ?>
                            <?php echo DwHtml::buttonTable('Modificar perfil', "sistema/perfiles/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                            <?php if($perfil->estado == Perfil::ACTIVO) { ?>
                                <?php echo DwHtml::buttonTable('Inactivar perfil', "sistema/perfiles/estado/inactivar/$key_inac/", null, 'success', 'fa-flag'); ?>
                            <?php } else { ?>
                                <?php echo DwHtml::buttonTable('Reactivar perfil', "sistema/perfiles/estado/reactivar/$key_reac/", null, 'danger', 'fa-flag'); ?>
                            <?php } ?>
                        </td>
                    </tr>
                    <?php $perfiles->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$perfiles, 'url'=>"sistema/perfiles/listar/$order/")); ?>

</div>