<header class="navbar navbar-inverse navbar-fixed-top user-nav" role="banner">
    
    <div class="container" style="margin-top: 0.5%">
        
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="../" class="navbar-brand"><?php echo APP_NAME; ?></a>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <?php echo DwMenu::frontend(); ?>
            <ul class="nav navbar-nav navbar-right">
                <li><?php echo DwHtml::link("sistema/login/entrar/", 'Ingresar'); ?>     </li>                
            </ul>
        </nav>
        
    </div>            
    
</header>